name: 'Skopeo Sync Action'
description: 'Sync images by skopeo'
author: 'Lemon'

branding:
  icon: 'package'
  color: 'blue'

# Define your inputs here.
inputs:
  auth_file:
    description: 'Auth file path, only support YAML'
    required: false
  images_file:
    description: 'Sync images config file path, only support YAML'
    required: true
    default: './images.yml'
  skip_error:
    description: 'If set true, any error during copying of images will ignored'
    required: true
    default: 'true'

runs:
  using: node20
  main: dist/index.js
